export const LAWYER_LIST = [
    {
        name: "Joey",
        case_type: "Criminal",
        id: "1",
        email: "ananth@gmail.com",
        phone_no: 1234567890,
        city: "Chennai",
        rating: 4,
      },
      {
        name: "Rajesh",
        case_type: "Civil",
        id: "1",
        email: "ananth@gmail.com",
        phone_no: 1234567890,
        city: "Bangalore",
        rating: 5,
      },
      {
        name: "Penny",
        case_type: "Civil",
        id: "1",
        email: "ananth@gmail.com",
        phone_no: 1234567890,
        city: "Mumbai",
        rating: 3,
      },
      {
        name: "Chandler",
        case_type: "Criminal/Civil",
        id: "1",
        email: "ananth@gmail.com",
        phone_no: 1234567890,
        city: "Kolkatta",
        rating: 5,
      },
      {
        name: "Leonard",
        case_type: "Criminal/Civil",
        id: "1",
        email: "ananth@gmail.com",
        phone_no: 1234567890,
        city: "Goa",
        rating: 3,
      },
];